require: rubocop-rspec

AllCops:
  RunRailsCops: true

  Include:
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Style/AlignHash:
  EnforcedColonStyle: table

Style/Encoding:
  EnforcedStyle: when_needed

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false
